trigger:
- main

pool:
  name: mac

variables:
  dockerImageName: myapp
  dockerImageTag: latest

steps:
- script: docker info
  displayName: 'Docker info'

- script: docker system df
  displayName: 'Disk usage'

- script: docker images --format "{{.Repository}}:{{.Tag}} {{.Size}}" | sort -k2 -h
  displayName: 'Sort by size'

- script: |
    docker build -t $(dockerImageName):$(dockerImageTag) .
  displayName: 'Docker Build'

# - script: |
#     echo "$(dockerPassword)" | docker login -u "$(dockerUsername)" --password-stdin
#     docker push $(dockerImageName):$(dockerImageTag)
#   displayName: 'Docker Push'
#   condition: and(succeeded(), eq(variables['dockerPush'], 'true'))
