trigger:
- main

pool:
  name: mac-home

variables:
  dockerImageName: myapp
  dockerImageTag: latest
  fullImageName: $(dockerImageName):$(dockerImageTag)

jobs:
- job: DockerDiagnostics
  displayName: "Docker Diagnostics"

  steps:
  - script: docker info
    displayName: 'Docker info'

  - script: docker system df
    displayName: 'Disk usage'

  - script: docker images --format "{{.Repository}}:{{.Tag}} {{.Size}}" | sort -k2 -h
    displayName: 'Sort by size'

- job: BuildImage
  displayName: "🏗️ Build Docker Image"
  dependsOn: DockerDiagnostics
  steps:
  - script: docker build -t $(fullImageName) .
    displayName: 'Build Image'
  # - script: |
  #     docker build -t $(dockerImageName):$(dockerImageTag) .
  #   displayName: 'Docker Build'

# - script: |
#     echo "$(dockerPassword)" | docker login -u "$(dockerUsername)" --password-stdin
#     docker push $(dockerImageName):$(dockerImageTag)
#   displayName: 'Docker Push'
#   condition: and(succeeded(), eq(variables['dockerPush'], 'true'))
