# trigger:
# - main

pool:
  name: test

trigger: none

parameters:
  - name: stack_names
    type: string
    default: "prod-minivan-api-new-app-ecs-service"
  - name: active
    type: string
    default: "true"
  - name: region
    type: string
    default: "us-east-1"

steps:
  - checkout: self

  # - task: DockerInstaller@0

  # - task: aws-actions/configure-aws-credentials@v1
  #   inputs:
  #     role-to-assume: arn:aws:iam::34545343435:role/AzureDevOpsEcsToggleRole
  #     aws-region: ${{ parameters.region }}

  - script: |
      docker build -t ecs-toggle ./docker
    displayName: 'Build Docker image'

  - script: |
      docker run --rm \
        -e AWS_REGION=${{ parameters.region }} \
        -e STACK_NAMES="${{ parameters.stack_names }}" \
        -e ACTIVE="${{ parameters.active }}" \
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
        -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
        ecs-toggle
    displayName: 'Run ECS Toggle via Docker'
